### ISSUE TITLE
Retain scroll position after switching to other screens - Inefficient App Flow

### ISSUE THREAD

**Issue by doggydon** [meow-it/meow-client#4]
Steps to reproduce:
* Reload the page
* Scroll down to last meow
* Click on `user options` (Profile Picture)
* Close the menu

Now, the scroll position is lost and the user has to scroll again to the bottom. Maybe try storing the scroll position in the Indexed DB

**Comment by tharunoptimus** [comment]
Thanks!
Working on it...
